version: '3.9'

services:
  virtual-ta:
    build: .
    container_name: tds-virtual-ta
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
