import os


class Settings:
    # API Configuration
    API_KEY = os.getenv("OPENAI_API_KEY", "")
    API_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")

    # Embedding and Similarity
    VECTOR_DIMENSION = 384  # Embedding size for all-MiniLM-L6-v2
    MATCH_THRESHOLD = 0.35  # Similarity cutoff for relevant results

    # Paths for index and metadata
    INDEX_FILE = "app/models/virtual_ta_index.faiss"
    METADATA_FILE = "app/models/virtual_ta_metadata.json"

    # JSON Schema definition for chatbot response
    OUTPUT_STRUCTURE = {
        "type": "json_schema",
        "json_schema": {
            "schema": "http://json-schema.org/draft-07/schema#",
            "name": "ChatReply",
            "strict": True,
            "description": "JSON format for the chatbot's response in the course assistant API.",
            "schema": {
                "type": "object",
                "properties": {
                    "answer": {
                        "type": "string",
                        "description": "Response generated by the assistant.",
                    },
                    "links": {
                        "type": "array",
                        "description": "Citations or resources referenced in the response.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "url": {
                                    "type": "string",
                                    "description": "Link to the referenced material.",
                                },
                                "text": {
                                    "type": "string",
                                    "description": "Brief title or description of the resource.",
                                },
                            },
                            "required": ["url", "text"],
                            "additionalProperties": False,
                        },
                    },
                },
                "required": ["answer", "links"],
                "additionalProperties": False,
            },
        },
    }

